### ISSUE TITLE
libraries should not set android:allowBackup

### ISSUE THREAD

**Issue by TecMunky** [sirmamedical/diabetes-m-addon-example#3]
When trying to integrate this API into our project, we encountered a conflict in the AndroidManifest.xml file.  Our project has android:allowBackup set to false.  Apparently your library has this set to true.

Everything I know and have read about this indicates libraries should not set this at all.

**Comment by TecMunky** [comment]
https://android.jlelse.eu/2-lines-in-manifest-to-remove-when-sharing-your-android-library-565d4c4af04a

**Comment by sirmamedical** [comment]
Thank you. Fixed!
